name = "TempestSDR"
uuid = "a2deda47-164f-4e4d-810f-425bbd57e6e7"
authors = ["Robin Gerzaguet <robin.gerzaguet@irisa.fr> and contributors"]
version = "0.1.0"

[deps]
AbstractSDRs = "0bdde9fc-719a-4dc7-8589-49ca6634fa6b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DigitalComm = "a7b11256-881b-11e9-3aff-ff4a76f1bfae"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Sixel = "45858cf5-a6b0-47a3-bbea-62219f50df47"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
