name = "TempestSDR"
uuid = "a2deda47-164f-4e4d-810f-425bbd57e6e7"
authors = ["Robin Gerzaguet <robin.gerzaguet@irisa.fr> and contributors"]
version = "0.8.0"

[deps]
AbstractSDRs = "0bdde9fc-719a-4dc7-8589-49ca6634fa6b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DigitalComm = "a7b11256-881b-11e9-3aff-ff4a76f1bfae"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
AbstractSDRs = "0.5"
DSP = "0.7.8"
DigitalComm = "1.1"
FFTW = "1.6"
GLMakie = "0.8.5"
Gtk = "1.3"
ImageFiltering = "0.7"
ImageInTerminal = "0.4.8"
ImageView = "0.11"
Images = "0.25, 0.26"
Makie = "0.19"
Reexport = "1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
